#!/bin/bash 
####################################################################
####################################################################
# Scripts that updates dynamic DNS servers using HTTPS via CURL.
# Curl is a required package. Please make sure it's installed!
# Currently supports Internet.bs and NO-IP.com providers.
# Custom parameters are set in /etc/dynip_update.conf - PLESE UPDATE
# THAT FILE - DO NOT CHANGE THIS SCRIPT.
####################################################################
####################################################################
DATENOW="`date`"
# Serial 2014110601

# Include custom parameters for this script
source /etc/dynip_update.conf


get_ext_ip () {
# Get external IP even if under NAT
#$DIG +short myip.opendns.com @resolver1.opendns.com &
curl -s curlmyip.com &
wait ${!}
}

is_ip () {
# Regex to validate IP
echo $1 | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
}

notify () {
if [ $EMAILNOTIFICATION -eq 1 ]
   then
	echo -e "Subject:$1\n" | $SENDMAIL $EMAIL
   else
	echo -e "$1\n"
fi
}

update_ip () {
RESULT=$(curl -s -k -u "$USERNAME:$PASS" "$DYNIPPROV?hostname=$DYNHOSTNAME&myip=$CURR_IP")
if [[ `echo "$RESULT" | grep -c "good"` -ne 1 ]]
   then 
	notify "[WARNING] DNS update result from `hostname` for $DYNHOSTNAME is $RESULT. Investigation needed."
	exit 1
fi
}

store_ip () {
echo "$CURR_IP" > $P_IP
}

####################################################################
CURR_IP="$(is_ip "$(get_ext_ip)")"
P_IP=/etc/p_ip.txt
PREV_IP="`cat $P_IP`"

if [ -z "$CURR_IP" ]
   then notify "Unable to get current IP for `hostname` - $DYNHOSTNAME -> Aborting" ; exit 1
fi

if ! [ -f $P_IP ] || [ "$CURR_IP" != "$PREV_IP" ] 
   then 
	store_ip
	update_ip
	notify "New IP $EXTIP set for $DYNHOSTNAME - at `date "+%H:%M %d/%m/%Y"` from `hostname`"
fi


